# Generated by Django 2.1.4 on 2019-01-02 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190102_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='town',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 2, 20, 50, 59, 276920)),
        ),
    ]
